# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Spelman/UCSD Psychology and Neuroscience Summer Research Program
author: John Serences, Spring 2022
logo: logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: true

# parse:
#   myst_substitutions:
#     key: value
#     url_website: "[Class Website](https://ucsd-css-001.github.io)"


# Information about where the book exists on the web
repository:
  url: https://github.com/ucsd-spelman-summer-research/ucsd-spelman.github.io  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
